version: "3"
services:
  server_unicorn:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server_unicorn
    ports:
      - "8084:8084"
    restart: always
    volumes:
      - .:/app/
      - /app/node_modules
    env_file:
      - config.env
